export const templateCategories=[
  "All",
  "Portfolio",
  "CV / Resume",
  "Graduation",
  "Examination",
  "Seminar",
  "Workshop",
  "Competition",
  "School Event",
  "Khmer Event",
  "Celebration",
];

export const templateTypes = [
  "Graduation",
  "Seminar",
  "Competition",
  "Examination",
  "Workshop",
  "School Event",
  "Khmer Event",
];

export const templateStyles = [
  "Khmer",
  "Traditional",
  "Elegant",
  "Modern",
];

export const templateColors = [
  {
    name: "Purple",
    value: "#B294F0",
  },
  {
    name: "Pink",
    value: "#EC6A9E",
  },
  {
    name: "Blue",
    value: "#4DB8FF",
  },
  {
    name: "Yellow",
    value: "#FFC21C",
  },
  {
    name: "Green",
    value: "#35C97A",
  },
  {
    name: "Multi",
    value: "conic-gradient(#705AE0, #EC6A9E, #FFC21C, #35C97A, #4DB8FF, #705AE0)",
  },
];

export const templates = [
  {
    id: 1,
    title: "Creative Portfolio",
    description: "Design and present your creative ideas.",
    type: "Workshop",
    categories: ["Workshop"],
    styles: ["Modern"],
    color: "Pink",
    orientation: "Landscape",
    tags: ["Workshop", "Modern", "Creative"],
    users: 250,
    preview: {
      variant: "portfolio",
      background: "#FFF5F3",
      accent: "#E83246",
      secondary: "#FFC21C",
      kicker: "MY",
      title: "Creative\nPortfolio",
      subtitle: "Portfolio",
    },
  },
  {
    id: 2,
    title: "Frontend Examination",
    description: "Frontend examination backdrop with timer.",
    type: "Examination",
    categories: ["Examination"],
    styles: ["Modern"],
    color: "Yellow",
    orientation: "Landscape",
    tags: ["Examination", "Modern", "Timer"],
    users: 250,
    preview: {
      variant: "exam",
      background: "#FFFDF0",
      accent: "#705AE0",
      secondary: "#FFC21C",
      kicker: "FRONTEND",
      title: "EXAMINATION",
      timer: "01:30:00",
    },
  },
  {
    id: 3,
    title: "Graduation Day",
    description: "Celebrate a class milestone with a bright backdrop.",
    type: "Graduation",
    categories: ["Graduation", "Celebration"],
    styles: ["Elegant"],
    color: "Purple",
    orientation: "Portrait",
    tags: ["Graduation", "Elegant", "Class"],
    users: 195,
    preview: {
      background: "#F6F0FF",
      accent: "#705AE0",
      secondary: "#FFC21C",
      kicker: "CONGRATULATIONS",
      title: "Graduation\n2026",
      subtitle: "Your future starts here",
    },
  },
  {
    id: 4,
    title: "Creative Topic",
    description: "A playful doodle design for class presentations.",
    type: "Workshop",
    categories: ["Workshop"],
    styles: ["Modern"],
    color: "Pink",
    orientation: "Landscape",
    tags: ["Workshop", "Creative", "Doodle"],
    users: 250,
    preview: {
      variant: "topic",
      background: "#F5EEFF",
      accent: "#705AE0",
      secondary: "#FFC21C",
      kicker: "CLASS TOPIC",
      title: "Title\nTopic",
      subtitle: "Share your best idea",
    },
  },
  {
    id: 5,
    title: "Design Your Ideas",
    description: "Clean creative layout for brainstorming sessions.",
    type: "Workshop",
    categories: ["Workshop"],
    styles: ["Modern"],
    color: "Blue",
    orientation: "Landscape",
    tags: ["Workshop", "Ideas", "Modern"],
    users: 250,
    preview: {
      variant: "ideas",
      background: "#EEF8FF",
      accent: "#4B9FFF",
      secondary: "#705AE0",
      kicker: "TECH SEMINAR",
      title: "Build.\nLearn. Share.",
      subtitle: "Technology Seminar",
    },
  },
  {
    id: 6,
    title: "Travel Memory",
    description: "Warm event backdrop for memory sharing.",
    type: "Seminar",
    categories: ["Seminar"],
    styles: ["Modern"],
    color: "Yellow",
    orientation: "Landscape",
    tags: ["Seminar", "Memory", "Warm"],
    users: 250,
    preview: {
      variant: "travel",
      background: "#EEFFF7",
      accent: "#25A967",
      secondary: "#FFC21C",
      kicker: "2026",
      title: "Travel\nMemory",
      subtitle: "Best journey",
    },
  },
  {
    id: 7,
    title: "Cambodia Heritage",
    description: "Khmer-inspired cultural event backdrop.",
    type: "Khmer Event",
    categories: ["Khmer Event", "Celebration"],
    styles: ["Khmer", "Traditional"],
    color: "Green",
    orientation: "Landscape",
    tags: ["Khmer", "Cambodia", "Traditional"],
    users: 410,
    preview: {
      variant: "cambodia",
      background: "#EAF4E5",
      accent: "#177A51",
      secondary: "#D1A143",
      kicker: "TRADITION",
      title: "CAMBODIA",
      subtitle: "Khmer Heritage",
    },
  },
  {
    id: 8,
    title: "School Festival",
    description: "Fun backdrop for school activities.",
    type: "School Event",
    categories: ["School Event", "Celebration"],
    styles: ["Modern"],
    color: "Pink",
    orientation: "Landscape",
    tags: ["School", "Festival", "Celebration"],
    users: 320,
    preview: {
      background: "#FFF2F8",
      accent: "#EC6A9E",
      secondary: "#FFC21C",
      kicker: "WELCOME TO",
      title: "School\nFestival",
      subtitle: "Learn - Play - Celebrate",
    },
  },
  {
    id: 9,
    title: "Competition Night",
    description: "Bold stage-style layout for competitions.",
    type: "Competition",
    categories: ["Competition"],
    styles: ["Modern"],
    color: "Multi",
    orientation: "Landscape",
    tags: ["Competition", "Stage", "Bold"],
    users: 305,
    preview: {
      background: "#F7F5FF",
      accent: "#705AE0",
      secondary: "#EC6A9E",
      kicker: "FINAL ROUND",
      title: "Competition\nNight",
      subtitle: "Show your talent",
    },
  },
  {
    id: 10,
    title: "Exam Countdown",
    description: "Simple examination backdrop with live timer.",
    type: "Examination",
    categories: ["Examination"],
    styles: ["Modern"],
    color: "Blue",
    orientation: "Landscape",
    tags: ["Examination", "Timer", "Clean"],
    users: 305,
    preview: {
      background: "#F0F8FF",
      accent: "#705AE0",
      secondary: "#FFC21C",
      kicker: "FINAL EXAMINATION",
      title: "Good Luck!",
      timer: "02:00:00",
    },
  },
  {
    id: 11,
    title: "Khmer Cultural Night",
    description: "Traditional Khmer event backdrop.",
    type: "Khmer Event",
    categories: ["Khmer Event"],
    styles: ["Khmer", "Traditional"],
    color: "Yellow",
    orientation: "Landscape",
    tags: ["Khmer", "Traditional", "Cultural"],
    users: 275,
    preview: {
      background: "#FFF8E3",
      accent: "#8E3D30",
      secondary: "#D6A329",
      kicker: "KHMER CULTURAL",
      title: "Heritage\nNight",
      subtitle: "Celebrate Cambodian culture",
    },
  },
  {
    id: 12,
    title: "Modern Student Event",
    description: "A colorful template for student events.",
    type: "School Event",
    categories: ["School Event"],
    styles: ["Modern"],
    color: "Multi",
    orientation: "Landscape",
    tags: ["School", "Student", "Modern"],
    users: 230,
    preview: {
      background: "#F7F5FF",
      accent: "#705AE0",
      secondary: "#FFC21C",
      kicker: "ISTAD",
      title: "Student\nEvent",
      subtitle: "Learn - Connect - Grow",
    },
  },
];
