// Generated by scripts/build-dark-artwork.mjs
import light0 from '../assets/Website/Nav/NavbarBg.svg';
import dark0 from './artwork/Nav/NavbarBg.svg';
import light1 from '../assets/Website/LandingPage/Hero-Section/OuterHeroVector.svg';
import dark1 from './artwork/LandingPage/Hero-Section/OuterHeroVector.svg';
import light2 from '../assets/Website/LandingPage/Hero-Section/MiddleHeroVector.svg';
import dark2 from './artwork/LandingPage/Hero-Section/MiddleHeroVector.svg';
import light3 from '../assets/Website/LandingPage/Hero-Section/InnerHeroVector.svg';
import dark3 from './artwork/LandingPage/Hero-Section/InnerHeroVector.svg';
import light4 from '../assets/Website/LandingPage/Hero-Section/HeroSolidVector.svg';
import dark4 from './artwork/LandingPage/Hero-Section/HeroSolidVector.svg';
import light5 from '../assets/Website/LandingPage/Hero-Section/HeroDashedVector.svg';
import dark5 from './artwork/LandingPage/Hero-Section/HeroDashedVector.svg';
import light6 from '../assets/Website/LandingPage/Hero-Section/Stats/HeroStatsBg.svg';
import dark6 from './artwork/LandingPage/Hero-Section/Stats/HeroStatsBg.svg';
import light7 from '../assets/Website/LandingPage/Hero-Section/Stats/PurpleBackground.svg';
import dark7 from './artwork/LandingPage/Hero-Section/Stats/PurpleBackground.svg';
import light8 from '../assets/Website/LandingPage/Hero-Section/Stats/YellowBackground.svg';
import dark8 from './artwork/LandingPage/Hero-Section/Stats/YellowBackground.svg';
import light9 from '../assets/Website/LandingPage/PopularTemplates/PopularTemplateTopWave.svg';
import dark9 from './artwork/LandingPage/PopularTemplates/PopularTemplateTopWave.svg';
import light10 from '../assets/Website/LandingPage/PopularTemplates/PopularTemplateLowerWave.svg';
import dark10 from './artwork/LandingPage/PopularTemplates/PopularTemplateLowerWave.svg';
import light11 from '../assets/Website/LandingPage/WhyChooseVisora/WhyChooseVisoraLinear.svg';
import dark11 from './artwork/LandingPage/WhyChooseVisora/WhyChooseVisoraLinear.svg';
import light12 from '../assets/Website/LandingPage/CreateWithoutLimits/YellowBlob.svg';
import dark12 from './artwork/LandingPage/CreateWithoutLimits/YellowBlob.svg';
import light13 from '../assets/Website/LandingPage/CreateWithoutLimits/PurpleBlob.svg';
import dark13 from './artwork/LandingPage/CreateWithoutLimits/PurpleBlob.svg';
import light14 from '../assets/Website/LandingPage/CreateWithoutLimits/YellowCardBlob(WithoutLimits).svg';
import dark14 from './artwork/LandingPage/CreateWithoutLimits/YellowCardBlob(WithoutLimits).svg';
import light15 from '../assets/Website/LandingPage/CreateWithoutLimits/PurpleCard(WithoutLimits).svg';
import dark15 from './artwork/LandingPage/CreateWithoutLimits/PurpleCard(WithoutLimits).svg';
import light16 from '../assets/Website/LandingPage/CreateWithoutLimits/SoftGreenCard(WithoutLimits).svg';
import dark16 from './artwork/LandingPage/CreateWithoutLimits/SoftGreenCard(WithoutLimits).svg';
import light17 from '../assets/Website/LandingPage/CreateWithoutLimits/SoftRedCard(WithoutLimits).svg';
import dark17 from './artwork/LandingPage/CreateWithoutLimits/SoftRedCard(WithoutLimits).svg';
import light18 from '../assets/Website/LandingPage/CreateWithoutLimits/MajenticCard(WithoutLimits).svg';
import dark18 from './artwork/LandingPage/CreateWithoutLimits/MajenticCard(WithoutLimits).svg';
import light19 from '../assets/Website/LandingPage/CreateWithoutLimits/CyanCard(WithoutLimits).svg.svg';
import dark19 from './artwork/LandingPage/CreateWithoutLimits/CyanCard(WithoutLimits).svg.svg';
import light20 from '../assets/Website/LandingPage/HowItWorks/FirstRactangle.svg';
import dark20 from './artwork/LandingPage/HowItWorks/FirstRactangle.svg';
import light21 from '../assets/Website/LandingPage/HowItWorks/2ndRactangle.svg';
import dark21 from './artwork/LandingPage/HowItWorks/2ndRactangle.svg';
import light22 from '../assets/Website/LandingPage/HowItWorks/3rdRactangle.svg';
import dark22 from './artwork/LandingPage/HowItWorks/3rdRactangle.svg';
import light23 from '../assets/Website/LandingPage/HowItWorks/Top-bg.svg';
import dark23 from './artwork/LandingPage/HowItWorks/Top-bg.svg';
import light24 from '../assets/Website/LandingPage/HowItWorks/BottomBg.svg';
import dark24 from './artwork/LandingPage/HowItWorks/BottomBg.svg';
import light25 from '../assets/Website/LandingPage/HowItWorks/Mountain.svg';
import dark25 from './artwork/LandingPage/HowItWorks/Mountain.svg';
import light26 from '../assets/Website/LandingPage/HowItWorks/01.svg';
import dark26 from './artwork/LandingPage/HowItWorks/01.svg';
import light27 from '../assets/Website/LandingPage/HowItWorks/02.svg';
import dark27 from './artwork/LandingPage/HowItWorks/02.svg';
import light28 from '../assets/Website/LandingPage/HowItWorks/03.svg';
import dark28 from './artwork/LandingPage/HowItWorks/03.svg';
import light29 from '../assets/Website/LandingPage/ExploreByEvents/TopBg(ExploreByEvents).svg';
import dark29 from './artwork/LandingPage/ExploreByEvents/TopBg(ExploreByEvents).svg';
import light30 from '../assets/Website/LandingPage/ExploreByEvents/LightPurpleBackground.svg';
import dark30 from './artwork/LandingPage/ExploreByEvents/LightPurpleBackground.svg';
import light31 from '../assets/Website/LandingPage/ExploreByEvents/ForegroundPurple.svg';
import dark31 from './artwork/LandingPage/ExploreByEvents/ForegroundPurple.svg';
import light32 from '../assets/Website/LandingPage/ExploreByEvents/LeftLayerBlur(ExploreByEvents).svg';
import dark32 from './artwork/LandingPage/ExploreByEvents/LeftLayerBlur(ExploreByEvents).svg';
import light33 from '../assets/Website/LandingPage/ExploreByEvents/CenterLayerBlur(ExploreByEvents).svg';
import dark33 from './artwork/LandingPage/ExploreByEvents/CenterLayerBlur(ExploreByEvents).svg';
import light34 from '../assets/Website/LandingPage/ExploreByEvents/RightLayerBlur.svg';
import dark34 from './artwork/LandingPage/ExploreByEvents/RightLayerBlur.svg';
import light35 from '../assets/Website/LandingPage/WhyChooseVisora/why-choose-blob.png';
import dark35 from '../assets/Website/LandingPage/WhyChooseVisora/WhyChooseVisoraRightBlob(DarkMode).svg';

export const darkAssets = {
  [light0]: dark0,
  [light1]: dark1,
  [light2]: dark2,
  [light3]: dark3,
  [light4]: dark4,
  [light5]: dark5,
  [light6]: dark6,
  [light7]: dark7,
  [light8]: dark8,
  [light9]: dark9,
  [light10]: dark10,
  [light11]: dark11,
  [light12]: dark12,
  [light13]: dark13,
  [light14]: dark14,
  [light15]: dark15,
  [light16]: dark16,
  [light17]: dark17,
  [light18]: dark18,
  [light19]: dark19,
  [light20]: dark20,
  [light21]: dark21,
  [light22]: dark22,
  [light23]: dark23,
  [light24]: dark24,
  [light25]: dark25,
  [light26]: dark26,
  [light27]: dark27,
  [light28]: dark28,
  [light29]: dark29,
  [light30]: dark30,
  [light31]: dark31,
  [light32]: dark32,
  [light33]: dark33,
  [light34]: dark34,
  [light35]: dark35,
};
