import { createContext, useContext, useMemo, useState } from "react";
import visoraLogo from "../../assets/Website/VisoraLogo.png";
const seedTemplates = [
  [
    "Graduation Ceremony 2026",
    "Sok Chantha",
    "sok.chantha@visora.com",
    "Graduation",
    "pending",
    "public",
    "2024-05-24",
    "10:30 AM",
    "yellow",
    visoraLogo,  
  ],
  [
    "Workshop on AI",
    "Dara Vannak",
    "dara.vannak@visora.com",
    "Workshop",
    "pending",
    "public",
    "2024-05-24",
    "9:15 AM",
    "blue",
  ],
  [
    "Khmer New Year Celebration",
    "Srey Pich",
    "srey.pich@visora.com",
    "Khmer Events",
    "pending",
    "public",
    "2024-05-23",
    "4:45 PM",
    "pink",
  ],
  [
    "Certificate of Achievement",
    "Vuthy Keo",
    "vuthy.keo@visora.com",
    "Examination",
    "pending",
    "public",
    "2024-05-23",
    "2:20 PM",
    "violet",
  ],
  [
    "Business Seminar Beige",
    "Nita Sorn",
    "nita.sorn@visora.com",
    "Seminar",
    "pending",
    "private",
    "2024-05-22",
    "11:05 AM",
    "peach",
  ],
  [
    "Creative Portfolio Red",
    "Bora Chea",
    "bora.chea@visora.com",
    "Portfolio",
    "pending",
    "public",
    "2024-05-22",
    "8:40 AM",
    "red",
  ],
  [
    "Children’s Day Celebration",
    "Ratha Kim",
    "ratha.kim@visora.com",
    "Others",
    "pending",
    "public",
    "2024-05-21",
    "5:15 PM",
    "green",
  ],
  [
    "Design Competition 2026",
    "Malis Phan",
    "malis.phan@visora.com",
    "Competition",
    "published",
    "public",
    "2024-05-20",
    "1:20 PM",
    "violet",
  ],
  [
    "Modern CV Portfolio",
    "Chan Dara",
    "chan.dara@visora.com",
    "Portfolio",
    "published",
    "public",
    "2024-05-19",
    "10:00 AM",
    "blue",
  ],
  [
    "Team Building Workshop",
    "Sophea Lim",
    "sophea.lim@visora.com",
    "Workshop",
    "published",
    "private",
    "2024-05-18",
    "3:40 PM",
    "green",
  ],
  [
    "Annual Seminar Poster",
    "Kosal Nhem",
    "kosal.nhem@visora.com",
    "Seminar",
    "rejected",
    "public",
    "2024-05-17",
    "8:30 AM",
    "peach",
  ],
  [
    "Final Exam Schedule",
    "Thyda Vong",
    "thyda.vong@visora.com",
    "Examination",
    "rejected",
    "public",
    "2024-05-16",
    "4:10 PM",
    "yellow",
  ],
].map(
  (
    [
      name,
      creator,
      email,
      category,
      status,
      visibility,
      createdAt,
      createdTime,
      shade,
      image,
    ],
    index,
  ) => ({
    id: index + 1,
    name,
    creator,
    email,
    category,
    status,
    visibility,
    createdAt,
    createdTime,
    shade,
    image,
    description: `A polished ${category.toLowerCase()} template for Visora.`,
  }),
);
const seedUsers = [
  ["Sok Chantha", "sok.chantha@visora.com", "Designer", "active", "2024-05-24"],
  ["Dara Vannak", "dara.vannak@visora.com", "Editor", "active", "2024-05-24"],
  ["Vuthy Keo", "vuthy.keo@visora.com", "Viewer", "active", "2024-05-23"],
  ["Nita Sorn", "nita.sorn@visora.com", "Designer", "active", "2024-05-22"],
  ["Bora Chea", "bora.chea@visora.com", "Editor", "active", "2024-05-21"],
  ["Ratha Kim", "ratha.kim@visora.com", "Viewer", "active", "2024-05-20"],
  ["Sophea Lim", "sophea.lim@visora.com", "Designer", "active", "2024-05-18"],
  ["Chan Dara", "chan.dara@visora.com", "Viewer", "active", "2024-05-17"],
].map(([name, email, role, status, joinedAt], index) => ({
  id: index + 1,
  name,
  email,
  role,
  status,
  joinedAt,
}));
const DataContext = createContext(null);
export function DashboardDataProvider({ children }) {
  const [templates, setTemplates] = useState(seedTemplates);
  const [users, setUsers] = useState(seedUsers);
  const categories = useMemo(
    () => [...new Set(templates.map((t) => t.category))],
    [templates],
  );
  const value = {
    templates,
    users,
    categories,
    addTemplate: (item) =>
      setTemplates((old) => [
        {
          ...item,
          id: Date.now(),
          createdAt: item.createdAt || "2024-05-25",
          createdTime: "12:00 PM",
          shade: "violet",
          description: `A polished ${item.category.toLowerCase()} template for Visora.`,
        },
        ...old,
      ]),
    updateTemplate: (id, patch) =>
      setTemplates((old) =>
        old.map((t) => (t.id === id ? { ...t, ...patch } : t)),
      ),
    deleteTemplate: (id) =>
      setTemplates((old) => old.filter((t) => t.id !== id)),
    addUser: (user) => setUsers((old) => [{ ...user, id: Date.now() }, ...old]),
    updateUser: (id, patch) =>
      setUsers((old) => old.map((u) => (u.id === id ? { ...u, ...patch } : u))),
    deleteUser: (id) => setUsers((old) => old.filter((u) => u.id !== id)),
  };
  return <DataContext.Provider value={value}>{children}</DataContext.Provider>;
}
export const useDashboardData = () => useContext(DataContext);
