export const shapeCatalog = [
  { id: "square", label: "Square", category: "Basic", w: 320, h: 320 },
  { id: "circle", label: "Circle", category: "Basic", w: 320, h: 320 },
  { id: "triangle", label: "Triangle", category: "Basic", w: 360, h: 320 },
  { id: "diamond", label: "Diamond", category: "Basic", w: 320, h: 360 },
  { id: "star", label: "Star", category: "Basic", w: 360, h: 360 },
  { id: "pill", label: "Pill", category: "Basic", w: 480, h: 220 },
  { id: "rectangle", label: "Rectangle", category: "Basic", w: 480, h: 280 },
  { id: "rounded-rectangle", label: "Rounded rectangle", category: "Basic", w: 480, h: 280 },
  { id: "right-triangle", label: "Right triangle", category: "Basic", w: 340, h: 320 },
  { id: "trapezoid", label: "Trapezoid", category: "Basic", w: 440, h: 280 },
  { id: "teardrop", label: "Teardrop", category: "Basic", w: 320, h: 320 },
  { id: "pentagon", label: "Pentagon", category: "Polygons", w: 360, h: 360 },
  { id: "hexagon", label: "Hexagon", category: "Polygons", w: 400, h: 350 },
  { id: "heptagon", label: "Heptagon", category: "Polygons", w: 360, h: 360 },
  { id: "octagon", label: "Octagon", category: "Polygons", w: 360, h: 360 },
  { id: "decagon", label: "Decagon", category: "Polygons", w: 360, h: 360 },
  { id: "parallelogram", label: "Parallelogram", category: "Polygons", w: 440, h: 280 },
  { id: "corner", label: "L-shape", category: "Polygons", w: 360, h: 360 },
  { id: "frame", label: "Frame", category: "Polygons", w: 380, h: 380 },
  { id: "arrow-right", label: "Right arrow", category: "Block Arrows", w: 520, h: 260 },
  { id: "arrow-left", label: "Left arrow", category: "Block Arrows", w: 520, h: 260 },
  { id: "arrow-up", label: "Up arrow", category: "Block Arrows", w: 260, h: 520 },
  { id: "arrow-down", label: "Down arrow", category: "Block Arrows", w: 260, h: 520 },
  { id: "arrow-left-right", label: "Left-right arrow", category: "Block Arrows", w: 540, h: 260 },
  { id: "arrow-up-down", label: "Up-down arrow", category: "Block Arrows", w: 260, h: 540 },
  { id: "arrow-quad", label: "Quad arrow", category: "Block Arrows", w: 400, h: 400 },
  { id: "arrow-notched", label: "Notched arrow", category: "Block Arrows", w: 520, h: 260 },
  { id: "home-plate", label: "Pentagon arrow", category: "Block Arrows", w: 440, h: 300 },
  { id: "chevron-right", label: "Chevron", category: "Block Arrows", w: 300, h: 360 },
  { id: "cross", label: "Plus", category: "Equation", w: 340, h: 340 },
  { id: "minus", label: "Minus", category: "Equation", w: 400, h: 120 },
  { id: "multiply", label: "Multiply", category: "Equation", w: 340, h: 340 },
  { id: "divide", label: "Divide", category: "Equation", w: 340, h: 340 },
  { id: "equal", label: "Equal", category: "Equation", w: 400, h: 260 },
  { id: "star", label: "5-point star", category: "Stars & Banners", w: 360, h: 360 },
  { id: "star-4", label: "4-point star", category: "Stars & Banners", w: 360, h: 360 },
  { id: "star-6", label: "6-point star", category: "Stars & Banners", w: 360, h: 360 },
  { id: "star-8", label: "8-point star", category: "Stars & Banners", w: 360, h: 360 },
  { id: "burst", label: "Explosion", category: "Stars & Banners", w: 380, h: 380 },
  { id: "lightning", label: "Lightning bolt", category: "Symbols", w: 300, h: 380 },
  { id: "heart", label: "Heart", category: "Symbols", w: 360, h: 330 },
  { id: "speech-bubble", label: "Speech bubble", category: "Callouts", w: 460, h: 340 },
  { id: "document", label: "Document", category: "Flowchart", w: 420, h: 320 },
];
export const shapeName = (shape) => shapeCatalog.find((item) => item.id === shape)?.label || "Shape";
export const shapeDefinition = (shape) => shapeCatalog.find((item) => item.id === shape);
